# Generated by Django 3.2.8 on 2021-10-10 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_responsibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Создатель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='responsibles',
            field=models.ManyToManyField(related_name='responsibles', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
    ]
