# Generated by Django 3.2.8 on 2021-10-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, upload_to='task-files/', verbose_name='Файл'),
        ),
    ]
